# language used for project
language:
  - python

# python versions supported
python:
  - 3.12

# install dependencies
install:
  - uv sync --frozen

services:
  # start postgres
  - postgresql

before_script:
  # create a testing database
  - psql -c 'create database mydiary_testing;' -U postgres

  # copy .env.example to .env in order to have proper db credentials
  - cp .env.example .env

script:
  # run tests with coverage
  - uv run pytest && uv run coverage report

after_success:
  # coverage report
  - uv tool install coveralls
  - uv tool run coveralls
